receivers:
  prometheusremotewrite:

processors:
  attributes/service_name:
    actions:
      - key: service.name
        from_attribute: job
        action: insert
  batch:
    timeout: 1m
  resource:
    attributes:
      - key: service.name
        from_attribute: job
        action: insert

exporters:
  otlp:
    endpoint: localhost:4317

service:
  pipelines:
    metrics:
      receivers: [prometheusremotewrite]
      processors: [resource, batch]
      exporters: [otlp]
