receivers:
  prometheusremotewrite:

processors:
  attributes/service_name:
    actions:
      - key: service.name
        from_attribute: job
        action: insert
  batch:

exporters:
  otlp:
    endpoint: localhost:4317

service:
  pipelines:
    metrics:
      receivers: [prometheusremotewrite]
      processors: [batch]
      exporters: [otlp]
