name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'main' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup OCB
        run: |
          curl --proto '=https' --tlsv1.2 -fL -o ocb \
          https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.96.0/ocb_0.96.0_linux_amd64
          chmod +x ocb

      - name: Build
        run: |
          ./ocb --config ./builder-config.yaml

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: otelcol-prometheus-remote-write-receiver
          path: ./otelcol-prometheus-remote-write-receiver

  build-docker-image:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_name == 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/rokoucha/otelcol-prometheus-remote-write-receiver:latest